# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc.chat_database import chat_database_pb2 as grpc_dot_chat__database_dot_chat__database__pb2


class ChatDatabaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChats = channel.unary_unary(
                '/chatdatabase.ChatDatabase/GetChats',
                request_serializer=grpc_dot_chat__database_dot_chat__database__pb2.GetChatsRequest.SerializeToString,
                response_deserializer=grpc_dot_chat__database_dot_chat__database__pb2.GetChatsResponse.FromString,
                )
        self.InsertChats = channel.unary_unary(
                '/chatdatabase.ChatDatabase/InsertChats',
                request_serializer=grpc_dot_chat__database_dot_chat__database__pb2.InsertChatsRequest.SerializeToString,
                response_deserializer=grpc_dot_chat__database_dot_chat__database__pb2.InsertChatsResponse.FromString,
                )


class ChatDatabaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatDatabaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChats,
                    request_deserializer=grpc_dot_chat__database_dot_chat__database__pb2.GetChatsRequest.FromString,
                    response_serializer=grpc_dot_chat__database_dot_chat__database__pb2.GetChatsResponse.SerializeToString,
            ),
            'InsertChats': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertChats,
                    request_deserializer=grpc_dot_chat__database_dot_chat__database__pb2.InsertChatsRequest.FromString,
                    response_serializer=grpc_dot_chat__database_dot_chat__database__pb2.InsertChatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatdatabase.ChatDatabase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatDatabase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatdatabase.ChatDatabase/GetChats',
            grpc_dot_chat__database_dot_chat__database__pb2.GetChatsRequest.SerializeToString,
            grpc_dot_chat__database_dot_chat__database__pb2.GetChatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatdatabase.ChatDatabase/InsertChats',
            grpc_dot_chat__database_dot_chat__database__pb2.InsertChatsRequest.SerializeToString,
            grpc_dot_chat__database_dot_chat__database__pb2.InsertChatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
